tap "universal-ctags/universal-ctags"
brew "bat"
brew "curl"
brew "direnv"
brew "exa"
brew "fd"
brew "gh"
brew "git"
brew "make"
brew "mysql"
brew "neovim"
brew "postgresql", restart_service: true
brew "ruby-build"
brew "rbenv"
brew "rbenv-gemset"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ripgrep"
brew "tmux"
brew "wget"
brew "yarn"
brew "z"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "font-jetbrains-mono-nerd-font"
cask "kiibohd-configurator"
cask "ngrok"
