#!/usr/bin/env sh

gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

cp .gitignore ~/.gitignore
cp .gitconfig ~/.gitconfig
cp .tmux.conf ~/.tmux.conf
cp .zshrc ~/.zshrc
cp .pryrc ~/.pryrc
cp .archipelago.json /Users/nick/Library/Application\ Support/Archipelago/config.json

chsh -s /bin/zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
