#!/usr/bin/env sh

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

ln -s ~/.dotfiles/.git_template ~/.git_template
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.gitignore ~/.gitignore
ln -s ~/.dotfiles/.irbrc ~/.irbrc
ln -s ~/.dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/.dotfiles/.zshrc ~/.zshrc
ln -s ~/.dotfiles/.config/bat ~/.config/bat
ln -s ~/.dotfiles/.config/nvim ~/.config/nvim
ln -s ~/.dotfiles/.archipelago.json /Users/nick/Library/Application\ Support/Archipelago/config.json
ln -s ~/.dotfiles/.oh-my-zsh/custom ~/.oh-my-zsh/custom
ln -s ~/.dotfiles/ghostty-config /Users/nick/Library/Application\ Support/com.mitchelh.ghostty/config

mkdir -p ~/.rbenv/plugins
git clone https://github.com/tpope/rbenv-ctags.git ~/.rbenv/plugins/rbenv-ctags
rbenv ctags
git clone https://github.com/rbenv/rbenv-default-gems.git $(rbenv root)/plugins/rbenv-default-gems
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

cargo install fozzie
cargo install ttags
cargo install fd-find
cargo install bat
cargo install eza
cargo install ripgrep

echo "gem-ttags\nripper-tags\nlanguage_server-protocol\nprism\nneovim\ntty-cursor\ntty-reader\ntty-screen\npastel" > $(rbenv root)/default-gems
